# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PPC_check_dialog_base.ui'
#
# Created: Thu Apr 27 08:59:24 2017
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PPC_checkDialogBase(object):
    def setupUi(self, PPC_checkDialogBase):
        PPC_checkDialogBase.setObjectName(_fromUtf8("PPC_checkDialogBase"))
        PPC_checkDialogBase.resize(456, 527)
        self.button_box = QtGui.QDialogButtonBox(PPC_checkDialogBase)
        self.button_box.setGeometry(QtCore.QRect(90, 480, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.tabWidget = QtGui.QTabWidget(PPC_checkDialogBase)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 441, 461))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_PPC = QtGui.QWidget()
        self.tab_PPC.setObjectName(_fromUtf8("tab_PPC"))
        self.lineEditCamDir = QtGui.QLineEdit(self.tab_PPC)
        self.lineEditCamDir.setGeometry(QtCore.QRect(140, 110, 221, 21))
        self.lineEditCamDir.setObjectName(_fromUtf8("lineEditCamDir"))
        self.groupBox = QtGui.QGroupBox(self.tab_PPC)
        self.groupBox.setGeometry(QtCore.QRect(30, 150, 371, 271))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.checkBoxGSD = QtGui.QCheckBox(self.groupBox)
        self.checkBoxGSD.setGeometry(QtCore.QRect(20, 110, 111, 17))
        self.checkBoxGSD.setObjectName(_fromUtf8("checkBoxGSD"))
        self.checkBoxSun = QtGui.QCheckBox(self.groupBox)
        self.checkBoxSun.setGeometry(QtCore.QRect(20, 143, 70, 16))
        self.checkBoxSun.setObjectName(_fromUtf8("checkBoxSun"))
        self.lineEditGSD = QtGui.QLineEdit(self.groupBox)
        self.lineEditGSD.setGeometry(QtCore.QRect(100, 110, 51, 20))
        self.lineEditGSD.setText(_fromUtf8(""))
        self.lineEditGSD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditGSD.setObjectName(_fromUtf8("lineEditGSD"))
        self.labelGSD = QtGui.QLabel(self.groupBox)
        self.labelGSD.setGeometry(QtCore.QRect(160, 111, 46, 20))
        self.labelGSD.setObjectName(_fromUtf8("labelGSD"))
        self.lineEditSUN = QtGui.QLineEdit(self.groupBox)
        self.lineEditSUN.setGeometry(QtCore.QRect(100, 140, 51, 20))
        self.lineEditSUN.setText(_fromUtf8(""))
        self.lineEditSUN.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditSUN.setObjectName(_fromUtf8("lineEditSUN"))
        self.labelSun = QtGui.QLabel(self.groupBox)
        self.labelSun.setGeometry(QtCore.QRect(160, 140, 46, 20))
        self.labelSun.setObjectName(_fromUtf8("labelSun"))
        self.checkBoxTilt = QtGui.QCheckBox(self.groupBox)
        self.checkBoxTilt.setGeometry(QtCore.QRect(20, 173, 70, 17))
        self.checkBoxTilt.setObjectName(_fromUtf8("checkBoxTilt"))
        self.labelTilt = QtGui.QLabel(self.groupBox)
        self.labelTilt.setGeometry(QtCore.QRect(160, 170, 46, 20))
        self.labelTilt.setObjectName(_fromUtf8("labelTilt"))
        self.lineEditTilt = QtGui.QLineEdit(self.groupBox)
        self.lineEditTilt.setGeometry(QtCore.QRect(100, 169, 51, 21))
        self.lineEditTilt.setText(_fromUtf8(""))
        self.lineEditTilt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTilt.setObjectName(_fromUtf8("lineEditTilt"))
        self.lineEditRef = QtGui.QLineEdit(self.groupBox)
        self.lineEditRef.setGeometry(QtCore.QRect(140, 200, 161, 20))
        self.lineEditRef.setText(_fromUtf8(""))
        self.lineEditRef.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditRef.setObjectName(_fromUtf8("lineEditRef"))
        self.checkBoxRef = QtGui.QCheckBox(self.groupBox)
        self.checkBoxRef.setGeometry(QtCore.QRect(20, 203, 111, 17))
        self.checkBoxRef.setObjectName(_fromUtf8("checkBoxRef"))
        self.checkBoxFile = QtGui.QCheckBox(self.groupBox)
        self.checkBoxFile.setGeometry(QtCore.QRect(20, 50, 231, 17))
        self.checkBoxFile.setObjectName(_fromUtf8("checkBoxFile"))
        self.checkBoxFormat = QtGui.QCheckBox(self.groupBox)
        self.checkBoxFormat.setGeometry(QtCore.QRect(20, 80, 241, 17))
        self.checkBoxFormat.setObjectName(_fromUtf8("checkBoxFormat"))
        self.checkBoxPic = QtGui.QCheckBox(self.groupBox)
        self.checkBoxPic.setGeometry(QtCore.QRect(20, 20, 231, 17))
        self.checkBoxPic.setObjectName(_fromUtf8("checkBoxPic"))
        self.checkBoxVoids = QtGui.QCheckBox(self.groupBox)
        self.checkBoxVoids.setGeometry(QtCore.QRect(20, 230, 231, 17))
        self.checkBoxVoids.setObjectName(_fromUtf8("checkBoxVoids"))
        self.labelCamDir = QtGui.QLabel(self.tab_PPC)
        self.labelCamDir.setGeometry(QtCore.QRect(40, 110, 101, 16))
        self.labelCamDir.setObjectName(_fromUtf8("labelCamDir"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_PPC)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 10, 371, 91))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.inShapeAPPC = QtGui.QComboBox(self.groupBox_2)
        self.inShapeAPPC.setGeometry(QtCore.QRect(20, 20, 331, 22))
        self.inShapeAPPC.setObjectName(_fromUtf8("inShapeAPPC"))
        self.useSelectedAPPC = QtGui.QCheckBox(self.groupBox_2)
        self.useSelectedAPPC.setGeometry(QtCore.QRect(30, 60, 181, 17))
        self.useSelectedAPPC.setObjectName(_fromUtf8("useSelectedAPPC"))
        self.radioButtonPPC_ob = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonPPC_ob.setGeometry(QtCore.QRect(230, 60, 61, 17))
        self.radioButtonPPC_ob.setObjectName(_fromUtf8("radioButtonPPC_ob"))
        self.radioButtonPPC_Nadir = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonPPC_Nadir.setGeometry(QtCore.QRect(300, 60, 82, 17))
        self.radioButtonPPC_Nadir.setObjectName(_fromUtf8("radioButtonPPC_Nadir"))
        self.pushButton_InputPPC = QtGui.QPushButton(self.tab_PPC)
        self.pushButton_InputPPC.setGeometry(QtCore.QRect(368, 110, 31, 21))
        self.pushButton_InputPPC.setObjectName(_fromUtf8("pushButton_InputPPC"))
        self.tabWidget.addTab(self.tab_PPC, _fromUtf8(""))
        self.tab_DB = QtGui.QWidget()
        self.tab_DB.setObjectName(_fromUtf8("tab_DB"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_DB)
        self.groupBox_7.setGeometry(QtCore.QRect(30, 10, 371, 91))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.inShapeDB = QtGui.QComboBox(self.groupBox_7)
        self.inShapeDB.setGeometry(QtCore.QRect(20, 20, 331, 22))
        self.inShapeDB.setObjectName(_fromUtf8("inShapeDB"))
        self.useSelectedDB = QtGui.QCheckBox(self.groupBox_7)
        self.useSelectedDB.setGeometry(QtCore.QRect(10, 60, 181, 17))
        self.useSelectedDB.setObjectName(_fromUtf8("useSelectedDB"))
        self.radioButtonDB_ob = QtGui.QRadioButton(self.groupBox_7)
        self.radioButtonDB_ob.setGeometry(QtCore.QRect(170, 50, 201, 17))
        self.radioButtonDB_ob.setObjectName(_fromUtf8("radioButtonDB_ob"))
        self.radioButtonDB_Nadir = QtGui.QRadioButton(self.groupBox_7)
        self.radioButtonDB_Nadir.setGeometry(QtCore.QRect(170, 70, 201, 17))
        self.radioButtonDB_Nadir.setObjectName(_fromUtf8("radioButtonDB_Nadir"))
        self.pushButton_uploadDB = QtGui.QPushButton(self.tab_DB)
        self.pushButton_uploadDB.setGeometry(QtCore.QRect(160, 120, 111, 23))
        self.pushButton_uploadDB.setObjectName(_fromUtf8("pushButton_uploadDB"))
        self.tabWidget.addTab(self.tab_DB, _fromUtf8(""))
        self.tab_Disk = QtGui.QWidget()
        self.tab_Disk.setObjectName(_fromUtf8("tab_Disk"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_Disk)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 130, 371, 91))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_Disk)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 10, 371, 101))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.textEdit = QtGui.QTextEdit(self.groupBox_4)
        self.textEdit.setGeometry(QtCore.QRect(20, 20, 341, 71))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.tabWidget.addTab(self.tab_Disk, _fromUtf8(""))
        self.tab_DBQC = QtGui.QWidget()
        self.tab_DBQC.setObjectName(_fromUtf8("tab_DBQC"))
        self.labelImageDir_2 = QtGui.QLabel(self.tab_DBQC)
        self.labelImageDir_2.setGeometry(QtCore.QRect(40, 110, 101, 16))
        self.labelImageDir_2.setObjectName(_fromUtf8("labelImageDir_2"))
        self.lineEditDBImageDir = QtGui.QLineEdit(self.tab_DBQC)
        self.lineEditDBImageDir.setGeometry(QtCore.QRect(120, 110, 241, 21))
        self.lineEditDBImageDir.setText(_fromUtf8(""))
        self.lineEditDBImageDir.setObjectName(_fromUtf8("lineEditDBImageDir"))
        self.pushButton_InputDB = QtGui.QPushButton(self.tab_DBQC)
        self.pushButton_InputDB.setGeometry(QtCore.QRect(368, 110, 31, 21))
        self.pushButton_InputDB.setObjectName(_fromUtf8("pushButton_InputDB"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_DBQC)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 10, 371, 91))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.inShapeAImage = QtGui.QComboBox(self.groupBox_3)
        self.inShapeAImage.setGeometry(QtCore.QRect(20, 20, 331, 22))
        self.inShapeAImage.setObjectName(_fromUtf8("inShapeAImage"))
        self.radioButtonDBQC_ob = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonDBQC_ob.setGeometry(QtCore.QRect(230, 60, 61, 17))
        self.radioButtonDBQC_ob.setObjectName(_fromUtf8("radioButtonDBQC_ob"))
        self.radioButtonDBQC_Nadir = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonDBQC_Nadir.setGeometry(QtCore.QRect(300, 60, 82, 17))
        self.radioButtonDBQC_Nadir.setObjectName(_fromUtf8("radioButtonDBQC_Nadir"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_DBQC)
        self.groupBox_6.setGeometry(QtCore.QRect(30, 150, 371, 231))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.checkBoxComp = QtGui.QCheckBox(self.groupBox_6)
        self.checkBoxComp.setGeometry(QtCore.QRect(20, 20, 301, 17))
        self.checkBoxComp.setObjectName(_fromUtf8("checkBoxComp"))
        self.tabWidget.addTab(self.tab_DBQC, _fromUtf8(""))

        self.retranslateUi(PPC_checkDialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("accepted()")), PPC_checkDialogBase.accept)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("rejected()")), PPC_checkDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(PPC_checkDialogBase)

    def retranslateUi(self, PPC_checkDialogBase):
        PPC_checkDialogBase.setWindowTitle(_translate("PPC_checkDialogBase", "PPC_check", None))
        self.groupBox.setTitle(_translate("PPC_checkDialogBase", "To be checked", None))
        self.checkBoxGSD.setText(_translate("PPC_checkDialogBase", "GSD", None))
        self.checkBoxSun.setText(_translate("PPC_checkDialogBase", "Sun angle", None))
        self.labelGSD.setText(_translate("PPC_checkDialogBase", "meters", None))
        self.labelSun.setText(_translate("PPC_checkDialogBase", "Degrees", None))
        self.checkBoxTilt.setText(_translate("PPC_checkDialogBase", "Tilt", None))
        self.labelTilt.setText(_translate("PPC_checkDialogBase", "Degrees", None))
        self.checkBoxRef.setText(_translate("PPC_checkDialogBase", "Reference system:", None))
        self.checkBoxFile.setText(_translate("PPC_checkDialogBase", "File format conforms to SDFE Standard", None))
        self.checkBoxFormat.setText(_translate("PPC_checkDialogBase", "Feature format conforms to SDFE Standard", None))
        self.checkBoxPic.setText(_translate("PPC_checkDialogBase", "Check image naming", None))
        self.checkBoxVoids.setText(_translate("PPC_checkDialogBase", "Footprint Void Check", None))
        self.labelCamDir.setText(_translate("PPC_checkDialogBase", "Path to camera dir:", None))
        self.groupBox_2.setTitle(_translate("PPC_checkDialogBase", "PPC or footprint file", None))
        self.useSelectedAPPC.setText(_translate("PPC_checkDialogBase", "Use only selected features", None))
        self.radioButtonPPC_ob.setText(_translate("PPC_checkDialogBase", "Oblique", None))
        self.radioButtonPPC_Nadir.setText(_translate("PPC_checkDialogBase", "Nadir", None))
        self.pushButton_InputPPC.setText(_translate("PPC_checkDialogBase", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_PPC), _translate("PPC_checkDialogBase", "#1 - Footprint", None))
        self.groupBox_7.setTitle(_translate("PPC_checkDialogBase", "Shapefile to upload to DB", None))
        self.useSelectedDB.setText(_translate("PPC_checkDialogBase", "Use only selected features", None))
        self.radioButtonDB_ob.setText(_translate("PPC_checkDialogBase", "Oblique ( footprint2017)", None))
        self.radioButtonDB_Nadir.setText(_translate("PPC_checkDialogBase", "Nadir ( ppc2017)", None))
        self.pushButton_uploadDB.setText(_translate("PPC_checkDialogBase", "Upload", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_DB), _translate("PPC_checkDialogBase", "#2 - Database", None))
        self.groupBox_5.setTitle(_translate("PPC_checkDialogBase", "To be checked", None))
        self.groupBox_4.setTitle(_translate("PPC_checkDialogBase", "Path to image dir:", None))
        self.textEdit.setHtml(_translate("PPC_checkDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Only for SDFE! </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Kør disk kontrol fra arbejds PC.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">###INFO###</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Disk), _translate("PPC_checkDialogBase", "#3 - Disk", None))
        self.labelImageDir_2.setText(_translate("PPC_checkDialogBase", "Image Dir Path:", None))
        self.pushButton_InputDB.setText(_translate("PPC_checkDialogBase", "...", None))
        self.groupBox_3.setTitle(_translate("PPC_checkDialogBase", "PPC or footprint Database", None))
        self.radioButtonDBQC_ob.setText(_translate("PPC_checkDialogBase", "Oblique", None))
        self.radioButtonDBQC_Nadir.setText(_translate("PPC_checkDialogBase", "Nadir", None))
        self.groupBox_6.setTitle(_translate("PPC_checkDialogBase", "To be checked", None))
        self.checkBoxComp.setText(_translate("PPC_checkDialogBase", "Check that every image has a assosiated footprint/PPC", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_DBQC), _translate("PPC_checkDialogBase", "#4 - DataBase QC", None))

